# Your Solution

version: '3'

services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://db_9aib_user:YRAJEVBpQPr8p3KPrtq3gev3qjNOV1qo@dpg-cs0402rtq21c739a45fg-a.singapore-postgres.render.com/db_9aib

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "4001:4001"
    environment:
      - PORT=4001
      - DATABASE_URL=postgresql://db_9aib_user:YRAJEVBpQPr8p3KPrtq3gev3qjNOV1qo@dpg-cs0402rtq21c739a45fg-a.singapore-postgres.render.com/db_9aib